//
// Created on 4/07/2018.
//

#ifndef DISCORDBOT_DISCORDAPI_H
#define DISCORDBOT_DISCORDAPI_H

#include "restAction.h"

#ifdef APIROUTE
#undef APIROUTE
#endif
#define APIROUTE(name) DISCORDAPI_ROUTE_ ## name

typedef enum {
	/* Misc */
	APIROUTE(MISC_GET_VOICE_REGIONS),
	APIROUTE(MISC_GATEWAY),
	APIROUTE(MISC_GATEWAY_BOT),
	APIROUTE(MISC_TRACK),

	/* Applications */
	APIROUTE(APPS_GET_BOT_APPLICATION),

	/* Self */
	APIROUTE(SELF_GET_SELF),
	APIROUTE(SELF_MODIFY_SELF),
	APIROUTE(SELF_GET_GUILDS),
	APIROUTE(SELF_LEAVE_GUILD),
	APIROUTE(SELF_GET_PRIVATE_CHANNELS),
	APIROUTE(SELF_CREATE_PRIVATE_CHANNEL),
	APIROUTE(SELF_GATEWAY_BOT),

	/* Users */
	APIROUTE(USERS_GET_USER),
	APIROUTE(USERS_GET_PROFILE),
	APIROUTE(USERS_GET_NOTE),
	APIROUTE(USERS_SET_NOTE),

	/* Guilds */
	APIROUTE(GUILDS_GET_GUILD),
	APIROUTE(GUILDS_MODIFY_GUILD),
	APIROUTE(GUILDS_GET_VANITY_URL),
	APIROUTE(GUILDS_CREATE_CHANNEL),
	APIROUTE(GUILDS_GET_CHANNELS),
	APIROUTE(GUILDS_MODIFY_CHANNELS),
	APIROUTE(GUILDS_MODIFY_ROLES),
	APIROUTE(GUILDS_GET_BANS),
	APIROUTE(GUILDS_UNBAN),
	APIROUTE(GUILDS_BAN),
	APIROUTE(GUILDS_KICK_MEMBER),
	APIROUTE(GUILDS_MODIFY_MEMBER),
	APIROUTE(GUILDS_MODIFY_SELF_NICK),
	APIROUTE(GUILDS_PRUNABLE_COUNT),
	APIROUTE(GUILDS_PRUNE_MEMBERS),
	APIROUTE(GUILDS_GET_WEBHOOKS),
	APIROUTE(GUILDS_GET_GUILD_EMBED),
	APIROUTE(GUILDS_MODIFY_GUILD_EMBED),
	APIROUTE(GUILDS_GET_GUILD_EMOTES),
	APIROUTE(GUILDS_GET_AUDIT_LOGS),
	APIROUTE(GUILDS_GET_VOICE_REGIONS),
	APIROUTE(GUILDS_GET_INTEGRATIONS),
	APIROUTE(GUILDS_CREATE_INTEGRATION),
	APIROUTE(GUILDS_DELETE_INTEGRATION),
	APIROUTE(GUILDS_MODIFY_INTEGRATION),
	APIROUTE(GUILDS_SYNC_INTEGRATION),
	APIROUTE(GUILDS_ADD_MEMBER_ROLE),
	APIROUTE(GUILDS_REMOVE_MEMBER_ROLE),

	/* Roles */
	APIROUTE(ROLES_GET_ROLES),
	APIROUTE(ROLES_CREATE_ROLE),
	APIROUTE(ROLES_GET_ROLE),
	APIROUTE(ROLES_MODIFY_ROLE),
	APIROUTE(ROLES_DELETE_ROLE),

	/* Channels */
	APIROUTE(CHANNELS_DELETE_CHANNEL),
	APIROUTE(CHANNELS_MODIFY_CHANNEL),
	APIROUTE(CHANNELS_SEND_TYPING),
	APIROUTE(CHANNELS_GET_PERMISSIONS),
	APIROUTE(CHANNELS_GET_PERM_OVERRIDE),
	APIROUTE(CHANNELS_GET_WEBHOOK),
	APIROUTE(CHANNELS_CREATE_WEBHOOK),
	APIROUTE(CHANNELS_CREATE_PERM_OVERRIDE),
	APIROUTE(CHANNELS_MODIFY_PERM_OVERRIDE),
	APIROUTE(CHANNELS_DELETE_PERM_OVERRIDE),

	/* Messages */
	APIROUTE(MESSAGES_SEND_MESSAGE),
	APIROUTE(MESSAGES_EDIT_MESSAGE),
	APIROUTE(MESSAGES_DELETE_MESSAGE),
	APIROUTE(MESSAGES_GET_PINNED_MESSAGES),
	APIROUTE(MESSAGES_ADD_PINNED_MESSAGE),
	APIROUTE(MESSAGES_REMOVE_PINNED_MESSAGE),
	APIROUTE(MESSAGES_ADD_REACTION),
	APIROUTE(MESSAGES_REMOVE_OWN_REACTION),
	APIROUTE(MESSAGES_REMOVE_REACTION),
	APIROUTE(MESSAGES_REMOVE_ALL_REACTIONS),
	APIROUTE(MESSAGES_GET_REACTION_USERS),
	APIROUTE(MESSAGES_GET_MESSAGE_HISTORY),
	APIROUTE(MESSAGES_GET_MESSAGE),
	APIROUTE(MESSAGES_DELETE_MESSAGES),

	/* Invites */
	APIROUTE(INVITES_GET_INVITE),
	APIROUTE(INVITES_DELETE_INVITE),
	APIROUTE(INVITES_GET_GUILD_INVITES),
	APIROUTE(INVITES_GET_CHANNEL_INVITES),
	APIROUTE(INVITES_CREATE_INVITE),

	/* Used to identify how many routes there are */
	APIROUTE(COUNT)
} discordAPIRoute;

#endif //DISCORDBOT_DISCORDAPI_H
